In [2]:
# 如何导入numpy
import numpy as np
# 如何检查numpy包的版本
print('numpy:', np.__version__)
# 检查可用的方法
print(dir(np))

numpy: 1.26.4
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_i

In [3]:
# 创建Python列表
python_list = [1,2,3,4,5]

# 检查数据类型
print('Type:', type (python_list)) # <class 'list'>
#
print(python_list) # [1, 2, 3, 4, 5]

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)  # [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

# 从Python列表创建NumPy(数值Python)数组

numpy_array_from_list = np.array(python_list)
print(type (numpy_array_from_list))   # <class 'numpy.ndarray'>
print(numpy_array_from_list) # array([1, 2, 3, 4, 5])

Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
# Python列表
python_list = [1,2,3,4,5]

numy_array_from_list2 = np.array(python_list, dtype=float)
print(numy_array_from_list2) # array([1., 2., 3., 4., 5.])

[1. 2. 3. 4. 5.]


In [5]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 我们总是可以使用tolist()将数组转换回Python列表。
np_to_list = numpy_array_from_list.tolist()
print(type (np_to_list))
print('一维数组:', np_to_list)
print('二维数组: ', numpy_two_dimensional_list.tolist())

<class 'list'>
一维数组: [1, 2, 3, 4, 5]
二维数组:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [7]:
# 从元组创建NumPy数组
# 在Python中创建元组
python_tuple = (1,2,3,4,5)
print(type (python_tuple)) # <class 'tuple'>
print('python_tuple: ', python_tuple) # python_tuple:  (1, 2, 3, 4, 5)

numpy_array_from_tuple = np.array(python_tuple)
print(type (numpy_array_from_tuple)) # <class 'numpy.ndarray'>
print('numpy_array_from_tuple: ', numpy_array_from_tuple) # numpy_array_from_tuple:  [1 2 3 4 5]

<class 'tuple'>
python_tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy_array_from_tuple:  [1 2 3 4 5]


In [9]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('nums的形状: ', nums.shape)
print(numpy_two_dimensional_list)
print('numpy_two_dimensional_list的形状: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
    [4,5,6,7],
    [8,9,10, 11]])
print(three_by_four_array.shape)

[1 2 3 4 5]
nums的形状:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
numpy_two_dimensional_list的形状:  (3, 3)
(3, 4)


In [8]:
int_lists = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_lists)
float_array = np.array(int_lists, dtype=float)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)

[-3 -2 -1  0  1  2  3]
int64
[-3. -2. -1.  0.  1.  2.  3.]
float64


In [10]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              [3, 4, 5],
                              [6, 7, 8]])

print('大小:', numpy_array_from_list.size) # 5
print('大小:', two_dimensional_list.size)  # 9

大小: 5
大小: 9


In [11]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('加法: ', numpy_array_from_list + 2)
print('加法: ', np.add(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
加法:  [3 4 5 6 7]
加法:  [3 4 5 6 7]


In [12]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('减法: ', numpy_array_from_list - 2)
print('减法: ', np.subtract(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
减法:  [-1  0  1  2  3]
减法:  [-1  0  1  2  3]


In [13]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('乘法: ', numpy_array_from_list * 2)
print('乘法: ', np.multiply(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
乘法:  [ 2  4  6  8 10]
乘法:  [ 2  4  6  8 10]


In [14]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('除法: ', numpy_array_from_list / 2)
print('除法: ', np.divide(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
除法:  [0.5 1.  1.5 2.  2.5]
除法:  [0.5 1.  1.5 2.  2.5]


In [15]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('模数: ', numpy_array_from_list % 2)
print('模数: ', np.mod(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
模数:  [1 0 1 0 1]
模数:  [1 0 1 0 1]


In [16]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('整除: ', numpy_array_from_list // 2)
print('整除: ', np.floor_divide(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
整除:  [0 1 1 2 2]
整除:  [0 1 1 2 2]


In [17]:
# 声明
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('原始数组: ', numpy_array_from_list)
print('指数: ', numpy_array_from_list ** 2)
print('指数: ', np.power(numpy_array_from_list, 2))

原始数组:  [1 2 3 4 5]
指数:  [ 1  4  9 16 25]
指数:  [ 1  4  9 16 25]


In [18]:
numpy_int_arr = np.array([1, 2, 3, 4])
numpy_float_arr = np.array([1.1, 2.0, 3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1, 2, 3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int64
float64
bool


In [19]:
numpy_int_arr = np.array([1, 2, 3, 4], dtype='float')
numpy_int_arr.astype('int').dtype
numpy_float_arr = np.array([1.1, 2.0, 3.2])
numpy_float_arr.astype('int').dtype
numpy_int_arr = np.array([-3, -2, 0, 1, 2, 3])
numpy_int_arr.astype('bool').dtype

dtype('bool')

In [20]:
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('形状: ', two_dimension_array.shape)
print('大小: ', two_dimension_array.size)
print('数据类型: ', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
形状:  (3, 3)
大小:  9
数据类型:  int64


In [23]:
# 二维数组
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('第一行:', first_row)
print('第二行:', second_row)
print('第三行: ', third_row)

第一行: [1 2 3]
第二行: [4 5 6]
第三行:  [7 8 9]


In [24]:
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('第一列:', first_column)
print('第二列:', second_column)
print('第三列: ', third_column)

第一列: [1 4 7]
第二列: [2 5 8]
第三列:  [3 6 9]


In [25]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('原始数组：', numpy_array_from_list)

# 第一个参数代表：起始位置
# 第二个参数代表：停止位置
# 第三个参数代表：步长
print('第一个参数代表：起始位置')
print('第二个参数代表：停止位置')
print('第三个参数代表：步长')
# 使用正index
ten_first_items = numpy_array_from_list[0:10]
print('前10项：', ten_first_items)
first_five_items = numpy_array_from_list[:5]
print('前5项：', first_five_items)
last_five_items = numpy_array_from_list[5:]
print('后5项：', last_five_items)
# 使用负index
last_five_items = numpy_array_from_list[-5:]
print('后5项：', last_five_items)

原始数组： [ 1  2  3  4  5  6  7  8  9 10]
第一个参数代表：起始位置
第二个参数代表：停止位置
第三个参数代表：步长
前10项： [ 1  2  3  4  5  6  7  8  9 10]
前5项： [1 2 3 4 5]
后5项： [ 6  7  8  9 10]
后5项： [ 6  7  8  9 10]


In [26]:
every_two_item = numpy_array_from_list[::2]
print('每隔一项：', every_two_item)

每隔一项： [1 3 5 7 9]


In [27]:
every_two_item = numpy_array_from_list[::2]
print('每隔一项：', every_two_item)

每隔一项： [1 3 5 7 9]


In [28]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(two_dimension_array)
print(two_dimension_array[1, 1])
print(two_dimension_array[1, 1:3])
print(two_dimension_array[1:3, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[5 6]
[[5 6]
 [8 9]]


In [29]:
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])
third_array = np.array([7, 8, 9])
print('第一个数组：', first_array)
print('第二个数组：', second_array)
print('第三个数组：', third_array)

第一个数组： [1 2 3]
第二个数组： [4 5 6]
第三个数组： [7 8 9]


In [30]:
horizontal_concat = np.hstack((first_array, second_array, third_array))
print('水平连接：', horizontal_concat)

水平连接： [1 2 3 4 5 6 7 8 9]


In [31]:
vertical_concat = np.vstack((first_array, second_array, third_array))
print('垂直连接：', vertical_concat)

垂直连接： [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('最小值：', numpy_array_from_list.min())
print('最大值：', numpy_array_from_list.max())
print('平均值：', numpy_array_from_list.mean())

最小值： 1
最大值： 10
平均值： 5.5
